import React,{useEffect,useRef,useState}from'react';import{createRoot}from'react-dom/client';import*as Cesium from'cesium';import 'cesium/Build/Cesium/Widgets/widgets.css';import{fetchRoutes,fetchStops,fetchVehicles}from'./api/client';import{tickTime}from'./simulation/timeEngine';import type{VehicleState}from'./types';import './style.css';
Cesium.Ion.defaultAccessToken=import.meta.env.VITE_CESIUM_ION_TOKEN??'';
function App(){const el=useRef<HTMLDivElement>(null);const viewer=useRef<Cesium.Viewer>();const ds=useRef(new Cesium.CustomDataSource('transport'));const vehDs=useRef(new Cesium.CustomDataSource('vehicles'));const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[time,setTime]=useState('08:00:00');const[playing,setPlaying]=useState(false);const[speed,setSpeed]=useState(60);const[metro,setMetro]=useState(true);const[tram,setTram]=useState(true);const[sel,setSel]=useState<any>();const[vehicles,setVehicles]=useState<VehicleState[]>([]);const[status,setStatus]=useState('initializing');
useEffect(()=>{if(!el.current)return;viewer.current=new Cesium.Viewer(el.current,{terrain:Cesium.Terrain.fromWorldTerrain(),timeline:false,animation:false});viewer.current.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(12.4964,41.9028,18000)});viewer.current.dataSources.add(ds.current);viewer.current.dataSources.add(vehDs.current);viewer.current.selectedEntityChanged.addEventListener(e=>setSel(e?.properties?.getValue(Cesium.JulianDate.now())??e));Promise.all([fetchRoutes(),fetchStops()]).then(([r,s])=>{draw(r,s);setStatus('ready')}).catch(e=>setStatus(e.message));return()=>viewer.current?.destroy()},[]);
function draw(routes:GeoJSON.FeatureCollection,stops:GeoJSON.FeatureCollection){ds.current.entities.removeAll();routes.features.forEach((f:any)=>{const mode=f.properties.mode; if((mode==='metro'&&!metro)||(mode==='tram'&&!tram))return; const coords=f.geometry.coordinates.map((c:number[])=>Cesium.Cartesian3.fromDegrees(c[0],c[1],mode==='metro'?-18:2));ds.current.entities.add({name:`${mode} ${f.properties.route_ids?.join(',')}`,polyline:{positions:coords,width:mode==='metro'?5:4,material:Cesium.Color.fromCssColorString(mode==='metro'?'#1976d2':'#e53935')}})});stops.features.forEach((f:any)=>ds.current.entities.add({name:f.properties.stop_name,position:Cesium.Cartesian3.fromDegrees(f.geometry.coordinates[0],f.geometry.coordinates[1],8),point:{pixelSize:7,color:Cesium.Color.WHITE,outlineColor:Cesium.Color.BLACK,outlineWidth:1},label:{text:f.properties.stop_name,font:'12px sans-serif',pixelOffset:new Cesium.Cartesian2(0,-18),show:false},properties:f.properties}))}
useEffect(()=>{let last=Date.now();const id=setInterval(()=>{if(playing){const now=Date.now();setTime(t=>tickTime(t,now-last,speed));last=now}},1000);return()=>clearInterval(id)},[playing,speed]);
useEffect(()=>{const modes=[...(metro?['metro']:[]),...(tram?['tram']:[])];fetchVehicles(date,time,modes).then(v=>{setVehicles(v);vehDs.current.entities.removeAll();v.forEach(x=>vehDs.current.entities.add({name:`${x.mode} ${x.route_id}`,position:Cesium.Cartesian3.fromDegrees(x.lon,x.lat,20),billboard:{image:x.mode==='metro'?'🚇':'🚊',scale:1.2},point:{pixelSize:12,color:Cesium.Color.YELLOW},properties:x}))}).catch(e=>setStatus(e.message))},[date,time,metro,tram]);
return <><div ref={el} className="map"/><aside className="panel"><h1>Rome Digital Twin</h1><p className="muted">Metro + Tram scheduled GTFS simulation</p><button onClick={()=>setPlaying(!playing)}>{playing?'Pause':'Play'}</button><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><input type="time" step="1" value={time} onChange={e=>setTime(e.target.value)}/><select value={speed} onChange={e=>setSpeed(+e.target.value)}><option value="1">1x</option><option value="10">10x</option><option value="60">60x</option><option value="300">300x</option></select><label><input type="checkbox" checked={metro} onChange={e=>setMetro(e.target.checked)}/> Metro</label><label><input type="checkbox" checked={tram} onChange={e=>setTram(e.target.checked)}/> Tram</label><input placeholder="Search station or line"/><h2>Status</h2><p>{status} · vehicles {vehicles.length}</p><h2>Inspector</h2><pre>{JSON.stringify(sel??vehicles[0]??{},null,2)}</pre><h2>Legend</h2><p><b className="blue">━</b> Metro underground · <b className="red">━</b> Tram surface</p></aside></>}
createRoot(document.getElementById('root')!).render(<App/>);
